name: Invoice Ninja
version: dev2
slug: invoiceninja
description: Invoice Ninja Addon for Home Assistant
url: https://github.com/DerPfandadler/My-Addons/tree/main/invoiceninja
arch:
  - aarch64
startup: services
boot: auto
ports:
  80/tcp: 8151
map:
  - config:rw
  - ssl
options:
  app_url: http://homeassistant.local
  db_username: username
  db_password: password
  db_database: name
  app_key: key
schema:
  app_url: str
  db_username: str
  db_password: str
  db_database: str
  app_key: str