name: Invoice Ninja
version: dev
slug: invoiceninja
description: Invoice Ninja Addon for Home Assistant
url: https://github.com/DerPfandadler/My-Addons/tree/main/invoiceninja
arch:
  - aarch64
startup: services
boot: auto
ports:
  80/tcp: 8151
map:
  - config:rw
  - ssl
options:
  application_url: 'http://homeassistant.local'
  db_username: ''
  db_password: ''
  db_database: ''
  app_key: ''
schema:
  application_url: str
  db_username: str
  db_password: str
  db_database: str
  app_key: str