name: Invoice Ninja
version: dev1
slug: invoiceninja
description: Invoice Ninja Addon for Home Assistant
url: https://github.com/DerPfandadler/My-Addons/tree/main/invoiceninja
arch:
  - aarch64
startup: services
boot: auto
ports:
  80/tcp: 8151
map:
  - config:rw
  - ssl
options:
  application_url: http://homeassistant.local
  db_username: username
  db_password: password
  db_database: name
  app_key: key
schema:
  application_url: str
  db_username: str
  db_password: str
  db_database: str
  app_key: str
environment:
  APP_URL: "{{ options.app_url }}"
  DB_HOST: "{{ options.db_host }}"
  DB_USERNAME: "{{ options.db_username }}"
  DB_PASSWORD: "{{ options.db_password }}"
  DB_DATABASE: "{{ options.db_database }}"
  APP_KEY: "{{ options.app_key }}"