name: Invoice Ninja
version: dev16
slug: invoiceninja
description: Invoice Ninja Addon for Home Assistant
url: https://github.com/DerPfandadler/My-Addons/tree/main/invoiceninja
arch:
  - aarch64
  - amd64
  - armv7
init: false
services:
  - mysql:need
hassio_api: true
ports:
  80/tcp: 8003

options:
  app_url: 'localhost'
  app_key: ''
  db_database: ''
  db_username: ''
  db_password: ''

schema:
  app_url: str
  app_key: str
  db_host: str
  db_database: str
  db_username: str
  db_password: str
