name: Invoice Ninja
version: dev2
slug: invoiceninja
description: Invoice Ninja Addon for Home Assistant
url: https://github.com/DerPfandadler/My-Addons/tree/main/invoiceninja
arch:
  - aarch64
startup: services
boot: auto
ports:
  80/tcp: 8003
map:
  - config:rw
  - ssl

options:
  # General Settings
  app_url: http://homeassistant.local
  app_key: your_key

  # Database Settings
  db_host: localhost
  db_port: 3306
  db_database: invoiceninja
  db_username: invoiceninja
  db_password: 43zB3dRL6KU3vOtMlUYfACLjmIlENVSW

  # Email Settings
  in_user_email: ''
  in_password: ''
  mail_mailer: log
  mail_host: smtp.mailtrap.io
  mail_port: 2525
  mail_username: null
  mail_password: null
  mail_encryption: null
  mail_from_address: 'user@example.com'
  mail_from_name: 'Self Hosted User'

  # MySQL Settings
  mysql_root_password: ninjaAdm1nPassword
  mysql_user: ninja
  mysql_password: ninja
  mysql_database: ninja

schema:
  # General Settings
  app_url: str
  app_key: str

  # Database Settings
  db_host: str
  db_port: int
  db_database: str
  db_username: str
  db_password: str

  # Email Settings
  in_user_email: str
  in_password: str
  mail_mailer: str
  mail_host: str
  mail_port: int
  mail_username: str
  mail_password: str
  mail_encryption: str
  mail_from_address: str
  mail_from_name: str

  # MySQL Settings
  mysql_root_password: str
  mysql_user: str
  mysql_password: str
  mysql_database: str
